import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { scriptLog } from '@config/src/cli/script-log.js';
import { escapeHtml } from '@config/src/views/html.js';
import { Eta, type TemplateFunction } from 'eta/core';
import type { Logger } from 'pino';

const here = dirname(fileURLToPath(import.meta.url));
export const defaultTemplatesDir = join(here, 'templates');
export const defaultGeneratedDir = join(here, 'generated');

const INCLUDE_CALL = /\b(?:include|includeAsync|layout)\(\s*(['"])([^'"]+)\1/g;

export interface CompileEtaOptions {
  readonly templatesDir?: string;
  readonly outDir?: string;
  /** CLI and watch: write each step to stderr. Tests leave this off. */
  readonly verbose?: boolean;
}

let etaLog: Logger | undefined;

const etaLogger = (): Logger => (etaLog ??= scriptLog('eta:compile'));

const say = (verbose: boolean | undefined, msg: string, extra?: object): void => {
  if (!verbose) return;
  if (extra) etaLogger().info(extra, msg);
  else etaLogger().info(msg);
};

const shout = (verbose: boolean | undefined, msg: string, extra?: object): void => {
  if (!verbose) return;
  if (extra) etaLogger().error(extra, msg);
  else etaLogger().error(msg);
};

const compilerEta = () =>
  new Eta({
    autoEscape: true,
    escapeFunction: escapeHtml,
    autoTrim: false,
    cache: false,
  });

const templateName = (templatesDir: string, filePath: string): string =>
  relative(templatesDir, filePath)
    .replace(/\.eta$/u, '')
    .split(sep)
    .join('/');

const walkEta = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walkEta(path)));
    else if (entry.isFile() && entry.name.endsWith('.eta')) files.push(path);
  }
  return files.sort();
};

const referencedNames = (source: string): string[] => {
  const names: string[] = [];
  INCLUDE_CALL.lastIndex = 0;
  let match: RegExpExecArray | null = INCLUDE_CALL.exec(source);
  while (match) {
    const name = match[2];
    if (name) names.push(name);
    match = INCLUDE_CALL.exec(source);
  }
  return names;
};

const functionFromBody = (name: string, body: string): TemplateFunction => {
  try {
    return new Function('it', 'options', body) as TemplateFunction;
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`Bad template syntax in ${name}: ${detail}`);
  }
};

const emitRegistry = (compiled: ReadonlyMap<string, string>): string => {
  const entries = [...compiled.entries()]
    .map(([name, body]) => {
      const key = JSON.stringify(name);
      const source = JSON.stringify(body);
      return `  ${key}: new Function('it', 'options', ${source}) as TemplateFunction`;
    })
    .join(',\n');
  return `// Generated by pnpm eta:compile. Do not edit.
import type { TemplateFunction } from 'eta/core';

export const compiledTemplates: Record<string, TemplateFunction> = {
${entries}
};
`;
};

export async function compileAll(
  options: CompileEtaOptions = {},
): Promise<Record<string, TemplateFunction>> {
  const templatesDir = options.templatesDir ?? defaultTemplatesDir;
  const outDir = options.outDir ?? defaultGeneratedDir;
  const started = Date.now();
  const verbose = options.verbose;
  say(verbose, 'compileAll start', { templatesDir, outDir });
  const eta = compilerEta();
  let files: string[];
  try {
    files = await walkEta(templatesDir);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    shout(verbose, 'walkEta failed', { templatesDir, code, err: error });
    if (code === 'ENOENT') throw new Error(`Templates directory is missing: ${templatesDir}`);
    throw error;
  }
  say(verbose, `found ${files.length} template file(s)`);
  for (const file of files) say(verbose, 'template path', { file });

  const sources = new Map<string, string>();
  for (const file of files) {
    const name = templateName(templatesDir, file);
    const source = await readFile(file, 'utf8');
    say(verbose, `read ${name}`, { bytes: Buffer.byteLength(source, 'utf8') });
    sources.set(name, source);
  }

  const known = new Set(sources.keys());
  say(verbose, `known template names (${known.size})`, { names: [...known] });
  for (const [name, source] of sources) {
    const includes = referencedNames(source);
    if (includes.length) say(verbose, `${name} includes`, { includes });
    for (const included of includes) {
      if (!known.has(included)) {
        shout(verbose, 'unknown include', { from: name, included });
        throw new Error(`Unknown include "${included}" from template "${name}"`);
      }
    }
  }

  const compiled = new Map<string, string>();
  const templates: Record<string, TemplateFunction> = {};
  for (const [name, source] of sources) {
    let body: string;
    try {
      body = eta.compileToString(source);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      shout(verbose, `compile failed: ${name}`, { err: error });
      throw new Error(`Bad template syntax in ${name}: ${detail}`);
    }
    say(verbose, `compiled ${name}`, { bodyBytes: Buffer.byteLength(body, 'utf8') });
    templates[name] = functionFromBody(name, body);
    compiled.set(name, body);
  }

  const registryPath = join(outDir, 'registry.ts');
  const registry = emitRegistry(compiled);
  await mkdir(outDir, { recursive: true });
  await writeFile(registryPath, registry, 'utf8');
  say(verbose, `wrote ${registryPath}`, {
    templates: compiled.size,
    bytes: Buffer.byteLength(registry, 'utf8'),
    ms: Date.now() - started,
  });
  return templates;
}

export async function watchTemplates(options: CompileEtaOptions = {}): Promise<void> {
  const { watch } = await import('node:fs');
  const templatesDir = options.templatesDir ?? defaultTemplatesDir;
  const verbose = { ...options, verbose: options.verbose ?? true };
  say(verbose.verbose, 'watchTemplates start', { templatesDir });
  await compileAll(verbose);
  watch(templatesDir, { recursive: true }, (event, filename) => {
    say(verbose.verbose, 'fs event', { event, filename: filename ?? null });
    if (!filename || !String(filename).endsWith('.eta')) {
      say(verbose.verbose, 'ignored (not an .eta file)');
      return;
    }
    say(verbose.verbose, `recompiling after change to ${filename}`);
    compileAll(verbose).catch((error: unknown) => {
      shout(true, 'watch compile failed', { err: error });
    });
  });
}

export async function main(argv: readonly string[]): Promise<void> {
  const watch = argv.includes('--watch') || argv.includes('--watch-and-server');
  const serve = argv.includes('--watch-and-server');
  const verbose = { verbose: true as const };
  say(true, 'main', {
    argv,
    cwd: process.cwd(),
    node: process.version,
    watch,
    serve,
  });
  if (watch) await watchTemplates(verbose);
  else await compileAll(verbose);
  if (!serve) {
    say(true, 'main finished (compile-only)');
    return;
  }
  const { spawn } = await import('node:child_process');
  const args = ['exec', 'tsx', 'watch', '--conditions=development', 'src/server.ts'];
  say(true, 'spawning server', { command: 'pnpm', args });
  const child = spawn('pnpm', args, { stdio: 'inherit' });
  child.on('error', (error) => {
    shout(true, 'failed to spawn server', { err: error });
  });
  child.on('exit', (code, signal) => {
    say(true, 'server process exited', { code, signal });
    process.exit(code ?? 1);
  });
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  await main(process.argv.slice(2));
}
